### ISSUE TITLE
side navigation scrolling issue if you have lots of components / folders

### ISSUE THREAD

**Issue by sturobson** [frctl/mandelbrot#18]
I've run into an issue where, if I have my components folder open and some other folders (say ~45 items) in the sidebar I can't scroll 'all the way' down to the items at the bottom and have to collapse my component folder to see other folders (like docs). This is on a 1920 x 1200 display.

removing the `height: 100%;` from the html fixes this but you lose the sticky header.

Could be flexbox 🎱

**Comment by allmarkedup** [comment]
@sturobson what browser is this in Stu? I can't seem to replicate it here in chrome, safari or firefox...

**Comment by sturobson** [comment]
@allmarkedup this 'bug' seems to be 'fixed' now - so I don't know what it was doing ... closing :)

**Comment by allmarkedup** [comment]
That's what I like to hear! :-) Cheers Stu.
