### ISSUE TITLE
Enhancement: Double-clicking a drag handle collapses/expands related UI area

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/mandelbrot#2]
_Making this request formal…_

Double clicking on a drag handle, UI conventions dictate that a related view is collapsed/expanded/auto-sized. As an enhancement, it would be great to see similar behaviour in this theme. To be clear, double clinking…
- the handle to the right of the sidebar, would hide the sidebar. Double clicking again would return it to its default position.
- the handle between the preview and template/notes area would hide the template/notes area. Double clicking it again would return it to its default position.
- the responsive preview handle, _when not in the full width position_, would return the preview to its full width.

**Comment by allmarkedup** [comment]
Implemented in b4f8faee14aaa0286cf72a0367900fa87d6e07e2
