### ISSUE TITLE
Update to Gulp 4 for build

### ISSUE THREAD

**Issue by allmarkedup** [frctl/mandelbrot#23]

**Comment by sturobson** [comment]
Hi @allmarkedup, what's needed here? I've been using Gulp v4 w/ client work for quite some time so might be able to help.

**Comment by allmarkedup** [comment]
Hey mate - it's nothing major but just was just a reminder to myself to tidy up (and document/comment) the build tasks really, including a Gulp 4 update as that is what I'm using everywhere else at the moment. Will happily accept pull requests! :-)
