### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by allmarkedup** [frctl/mandelbrot#27]

**Comment by ethikz** [comment]
Status?

**Comment by jackblackCH** [comment]
+1

**Comment by allmarkedup** [comment]
Status is still pending I'm afraid :-( It will be high up on the list when I get a bit more time to work on it!

**Comment by kalinchernev** [comment]
Hi, we made a [lunr search](https://ec-europa.github.io/europa-component-library/) for the components as part of the theme's override.
If you're interested in a similar thing, please give me some high-level ideas how this could be contributed back? (i.e. just adding it as new template or via some plugin system)
In our case, we make the search index and store in the build phase, which might actually be part of the fractal CLI or core.
At any case, if there's interest in having this ideas contributed back in any way. let me know :)

**Comment by ethikz** [comment]
@allmarkedup ?

**Comment by kalinchernev** [comment]
The final result can be seen and used via [this package](https://www.npmjs.com/package/@ec-europa/ecl-fractal-theme). This is [the theme itself](https://github.com/ec-europa/ecl-toolkit/tree/master/packages/ecl-fractal-theme).

**Comment by ethikz** [comment]
@kalinchernev I'll check it out!

**Comment by thisislawatts** [comment]
Thanks for the link @kalinchernev, good to see it within the context of the wider theme you're using.

How about inlining the search into the sidebar, like the lodash documentation? This implementation appears to be using react.

![Suggestion: Adding search functionality to Fractal within the sidebar](https://user-images.githubusercontent.com/472589/31279255-58d9d140-aaa0-11e7-9851-bb51e3ac88fa.gif)

**Comment by kalinchernev** [comment]
@thisislawatts actually it was like in the lodash in the [very first iteration](https://github.com/ec-europa/europa-component-library/pull/76). The trick is to work with the [results area](https://github.com/ec-europa/ecl-toolkit/blob/601a91ba377d152d9cf5e92735f3e72083e8a3db/packages/ecl-fractal-theme/assets/js/search.js#L17) :)

PS: The way we do it in the current implementation is good o' jquery, but you know if you had react it would be a different and more optimal way

**Comment by thisislawatts** [comment]
Great minds ;) Thanks for the links.

I'm not sure you'd want to add react just for this feature, only thought it was a good-to-know detail about Lodash's version. Not sure of the current status of this project, perhaps there's a wider rewrite underway at the moment to incorporate one of these 🔥  frameworks.

**Comment by marcelosomers** [comment]
Any updates on search? Is this planned for v2? I didn't see anything in the roadmap, but we are hoping not to have to fork mandelbrot to implement search ourselves.

**Comment by Dan9boi** [comment]
Any update on this issue? It's been a year, and we still would like a search :)

**Comment by Dan9boi** [comment]
could someone just review/merge https://github.com/frctl/mandelbrot/pull/74, it would solve this issue!
