### ISSUE TITLE
Enhancement: Support right-to-left languages

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/mandelbrot#3]
This has been on my mind a lot recently, but a fully i18n UI would be a welcome, and unique, addition.

While (I think) all labels and copy in the UI are currently user customisable, which is great for i18n, currently there is no means of adjusting the UI so that it works for right-to-left languages. I believe firstly, the theme needs to expose a configuration option that allows a user to enable right-to-left language direction. This in turn would set the `dir` attribute on the root `html` element to `rtf`.

Secondly, the UI styles need to ensure they work in both language direction contexts… which basically means avoiding the use of left or right positioning statements and, where such declarations are needed, ensuring these are within the respective `[dir="ltr|rtl"]` scopes.

Also, come to think of it, as well as `dir`, perhaps `lang` should be a config value too… seeing as this can effect things like hyphenation?

**Comment by allmarkedup** [comment]
Done and released in v0.2.11 thanks to your PR and a bit of JavaScript tinkering :-)
