### ISSUE TITLE
Code blocks in documentation should not overflow their container

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/mandelbrot#34]
![screen shot 2016-07-27 at 10 47 54](https://cloud.githubusercontent.com/assets/813383/17260875/b8351676-55ca-11e6-9646-614d08cdbeb4.png)

Will need to add a little `overflow: scroll` in the `.Prose` styles, I suspect.

@allmarkedup Feel free to assign this issue to me, if you like.

**Comment by allmarkedup** [comment]
Cheers @paulrobertlloyd but had to push out some other fixes/updates anyway so have fixed this up now.

**Comment by paulrobertlloyd** [comment]
👍🏻
