### ISSUE TITLE
Direct links to fragment identifiers in documents should override remembered page position

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/mandelbrot#39]
When creating documentation pages, it can be useful to add links to specific sections on other documentation pages. Marked adds `id`s to page headings, which makes doing this trivial. Nice!

However, Mandelbrot goes to great lengths to remember your last-visited page position. So, if you click on a link to a specific page fragment, but you have visited that page before, the fragment identifier is ignored. Bad Mandelbrot.

**Comment by allmarkedup** [comment]
Mandelbrot isn't actually doing anything to remember your page position! I suspect this is likely a bug to do with the Pjax-loading of pages. Along with all the other Pjax-related issues! I need to find a better way to handle the page change/reloading behaviour to be honest. But I'll add this to the bug list in the meantime.

**Comment by LeBenLeBen** [comment]
Could not reproduce this issue, when landing on the page the scroll is properly positioned according to the anchor. Tested in dev & prod mode, with Firefox, Chrome and Safari.
