### ISSUE TITLE
IE<=10 support / polyfills / preScripts, preStyles

### ISSUE THREAD

**Issue by tlenex** [frctl/mandelbrot#45]
Because mandelbrot theme uses `classList` which is unsupported by IE<9 and partially supported by IE10, page of style guide is left with `<html class="no-js" ...>` and causes some other rendering errors.

I can see three solutions:
1. Add polyfills to mandelbrot itself - no configuration available
2. Add support for 'preScripts' and 'preStyles' in mandelbrot's theme config, loaded at the beginigng of `<head>` tag, for low theme user (+ `default`) input
3. Leave it as is. User have to create new template just for adding support for target browsers - heavy theme user input

@allmarkedup which way suits you the most? I can make PR for 1. or 2.

**Comment by allmarkedup** [comment]
@tlenex thanks for looking at this. I think at this point I'd personally be in favour of option 1 as it would certainly be beneficial to all if the theme can be updated to work with older versions of IE.

I'm afraid that there may well be other issues apart from the use of classList in there that might cause you a few headaches in IE9 though :-( But any work you can do to improve the foundations would be much appreciated.

**Comment by LeBenLeBen** [comment]
Let's drop this one for the same reason as #46 in favor of all the other issues mentioning IE11.
