### ISSUE TITLE
Setting the default width for the preview viewport in url

### ISSUE THREAD

**Issue by alienlebarge** [frctl/mandelbrot#51]
Hello there,
I was wondering if there was a way to make links by specifying the width of the viewport [as patternlab does](http://patternlab.io/docs/pattern-linking.html#default-width).

This is something we often use when we send a link for validation. Our users are not so up to date with the concept of "Mobil First”. 😬 

## Additional info
This question was originally asked in frctl/fractal#204

**Comment by LeBenLeBen** [comment]
Moved back to main repo (monorepo)
