### ISSUE TITLE
Rename nav sections?

### ISSUE THREAD

**Issue by Bennethon** [frctl/mandelbrot#54]
Is it possible to rename the nav sections in the theme config? Or can it be done some other way? If not, I think that would be a great feature. Thanks!

**Comment by julkue** [comment]
👍

**Comment by mihkeleidast** [comment]
You can rename the components title in your fractal config file via:
```
fractal.components.set('label', 'Patterns');
```
and docs similarly:
```
fractal.docs.set('label', 'Docs');
```
