### ISSUE TITLE
Allow navigation with keyboard

### ISSUE THREAD

**Issue by julkue** [frctl/mandelbrot#58]
To navigate between components it would be helpful to have keyboard support

**Comment by LeBenLeBen** [comment]
@julmot would you like to share your idea about how this should be ideally implemented? I'm afraid it could cause issues with components that might bind some keyboard events.

**Comment by julkue** [comment]
Most likely with a `tabindex` attribute. I'm not sure how this behaves for keyboard events, when displayed within an iframe.

**Comment by LeBenLeBen** [comment]
Oh, I think I understand now. Groups are not accessible within the navigation because they are not made of focusable elements. This is actually a duplicated of #53. Feel free to reopen if I misunderstood your problem.
