### ISSUE TITLE
Apply indentation (beautifyHTML) after handlebars partials are included

### ISSUE THREAD

**Issue by krnlde** [frctl/mandelbrot#59]
Hey guys,
we use fractal in a big project and it works great. Thanks so for the great work. Unfortunately the mandelbrot theme seams to apply beautifyHTML before the handlebars partials are evaluated. Consider the following (simplified) usecase:

`example-component.hbs`
```hbs
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <span>Example Youtube Panel</span>
        {{> icon type="youtube" }}
      </h4>
    </div>
  </div>
</div>
```
We expected it to evaluate to:

`example-component.html`
```html
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <span>Example Youtube Panel</span>
        <svg>
          <use xlink:href="iconsprite.svg#youtube"></use>
        </svg>
      </h4>
    </div>
  </div>
</div>
```
but it actualy outputs:

`example-component.html`
```html
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <span>Example Youtube Panel</span>
        <svg>
  <use xlink:href="iconsprite.svg#youtube"></use>
</svg>
      </h4>
    </div>
  </div>
</div>
```

It looks like the beautifyHTML task is run before the handlebars partials are evaluated (it also doesn't convert the original indentation-characters from the partial). I will look into your code now and see if I can find any clues and maybe produce a PR on my own.

Cheers,
Kai

**Comment by LeBenLeBen** [comment]
I've made some tests and I don't get the exact same results, maybe it was improved since you opened this issue? All lines indentation are correct except the last one where the parent tag ends on the same line:

```html
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <span>Example Youtube Panel</span>
                <svg>
                    <use xlink:href="iconsprite.svg#youtube"></use>
                </svg> </h4>
        </div>
    </div>
</div>
```

It looks like this happens when the file/string of the partial included do not ends with an empty line. If you add an empty line the result is good:

```html
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <span>Example Youtube Panel</span>
                <svg>
                    <use xlink:href="iconsprite.svg#youtube"></use>
                </svg>
            </h4>
        </div>
    </div>
</div>
```

I'd say it's an issue with js-beautify since pasting the wrong one on https://beautifier.io/ doesn't fix the bad indentation.

**Comment by LeBenLeBen** [comment]
Indeed, this has been reported in https://github.com/beautify-web/js-beautify/issues/1468

**Comment by mihkeleidast** [comment]
Closing this since the reported issue has been fixed at some point and the remaining issue with misplaced closing tags is a js-beautify bug that we can't fix directly.
