### ISSUE TITLE
Better customization for theme

### ISSUE THREAD

**Issue by ethikz** [frctl/mandelbrot#66]
I'm just curious is if it's in the roadmap to allow creation of child themes or at least a simple way to override certain parts of the views.  For example, now in order to override I have to copy the file to my `overrides` folder but when the main theme is updated I might get breaking issues like here:

https://github.com/frctl/fractal/issues/270

Like you are able to extend in Handlebars, etc.

**Comment by LeBenLeBen** [comment]
I don't think we plan to go in that direction in a near future. The current setup allows complete customization which is great. It indeed comes with the drawbacks of having to carefully apply updates. We'll always be careful to avoid releasing breaking changes outside of major versions though.
