### ISSUE TITLE
Panel Resizing Doesn't Work in IE11

### ISSUE THREAD

**Issue by julkue** [frctl/mandelbrot#68]
The resize works with the navigation panel, but not with the two other resizable panels on the right side, e.g.:

![2017-08-23 10_15_52-cart page_ default _ de sede frontend component library - internet explorer](https://user-images.githubusercontent.com/8310677/29605699-3143e836-87ec-11e7-84ab-98c418839ce5.png)

What happens is that it marks the contents instead.

**Comment by patriknil90** [comment]
@julmot A little bit late to the party, but did you find a workaround?

**Comment by julkue** [comment]
@patriknil90 No, sorry

**Comment by TanyaScales** [comment]
@julmot, did you have any errors showing up in the console when this issue was happening?

**Comment by LeBenLeBen** [comment]
Released in 1.2.1
