### ISSUE TITLE
HTML/View/Context Code blocks collapsing whitespace

### ISSUE THREAD

**Issue by thisislawatts** [frctl/mandelbrot#69]
Locally I'm seeing Code blocks where the whitespace is being collapsed.

In the following .gif I toggle this rule on within the browser:
```css
.Code {
 white-space: pre;
}

```

![frctlcodeblocks](https://user-images.githubusercontent.com/472589/30855158-df514c64-a2ab-11e7-8379-d7af73d83d63.gif)

Fractal configuration:
- @frctl/consolidate: ^1.0.1
- @frctl/fractal: ^1.1.7
- [frctl-liquid](https://github.com/thisislawatts/frctl-liquid): ^0.1.1

Could it be the liquid adapter causing the issue? If so how come the Context tab is also affected.

**Comment by thisislawatts** [comment]
Some further information on this. It appears to happen when the view has been reloaded due to a file being changed.

In the following screencast:
1. Load up a component page (fillmurray optional)
2. Edit a source file to trigger an update on that component which reloads the view
3. Observe collapsed whitespace on your HTML/View/Context tabs
4. Use the sidebar to navigate back to same component

![frctlcodeblocks](https://user-images.githubusercontent.com/472589/30961917-bc0a0b66-a43f-11e7-8814-95cc14b8cd43.gif)

**Comment by dkhuntrods** [comment]
Hi @thisislawatts, can you confirm if you still get this behaviour in an incognito tab? We'd had a report of this, which was then closed by the user as being caused by a browser extension.

**Comment by thisislawatts** [comment]
Thanks for the follow up @dkhuntrods.

Apologies for missing that other issue. You're quite right, this appears to be happening within Chrome windows, where the __aXe – offered by Deque Systems__ extension is active.
