### ISSUE TITLE
Enhancement: Help page should still be reachable when custom docs are added

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/mandelbrot#7]
The default install shows some brief help text and a summary of the different status values. But if you add  any documentation, this page disappears. Maybe that’s fine. Or maybe, this page can include some (more) generic user-facing help, and be reachable from an icon in the header.

Maybe.

**Comment by allmarkedup** [comment]
I'm not sure about this. I think a help page is not a bad idea but I'd rather keep this as just default content if you haven't included a docs index page.

Closing for now.
