### ISSUE TITLE
Show a .json inside a new panel

### ISSUE THREAD

**Issue by acespace90** [frctl/mandelbrot#71]
I generated a new .json for each component with some extra data, I want to show it in a new panel. 

Now, I’ve created the panel with success but I don't know how to display inside it. I’m trying to look inside the source code of mandelbrot but I’m little bit confused. 

What I want to do is similar to panel "Context" in `mandelbrot/views/partials/browser/panel-context.nunj`

Can anyone help me?

**Comment by mihkeleidast** [comment]
Hi! Sorry for the (very) delayed response.

Let's do this by example: say you've added a `data.json` to your component folder.

then you'd need to add a theme override to your fractal config like so:
```
const myCustomisedTheme = require('@frctl/mandelbrot')({
    // 'data' is the new custom panel with custom contents.
    // the added template file 'panel-data.nunj' should be named accordingly
    // so if you want the new tab to be called "Lorem", the template should be named
    // 'panel-lorem.nunj' and 'lorem' should be added to this array
    panels: ['html', 'view', 'context', 'resources', 'info', 'notes', 'data']
});

// specify a directory to hold the theme override templates
myCustomisedTheme.addLoadPath(__dirname + '/theme');  

fractal.web.theme(myCustomisedTheme);
```

in that folder, you should add a file to `partials/browser` folder called `panel-data.nunj`, for example.

that file should have the following contents:
```
<div class="Browser-panel Browser-code" data-role="tab-panel" id="browser-{{ entity.id }}-panel-data">
    <code class="Code Code--lang-json">
        {% set compHandle = entity.component().handle %}
        {% for collection in entity.resources().items() %}
            {% if collection.size %}
                {% for resource in collection.items() %}
                    {% if resource.base == 'data.json' %}
                        <code class="Code Code--lang-{{ resource.lang }} FileBrowser-code">
                            <pre>{{ resource.contents | highlight(resource.lang) }}</pre>
                        </code>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endfor %}
    </code>
</div>
```
in this template we loop over the component assets (similarly as to what is done in the assets/resources tab), filter out the correct file and show the contents of that file.
