### ISSUE TITLE
iFrame sandbox attribute purpose

### ISSUE THREAD

**Issue by LeBenLeBen** [frctl/mandelbrot#76]
When browsing a Fractal instance in Firefox, I get the following warning in the console:

> An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.

The [HTML standard](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-sandbox) seems to describe this a little bit better:

> Setting both the allow-scripts and allow-same-origin keywords together when the embedded page has the same origin as the page containing the iframe allows the embedded page to simply remove the sandbox attribute and then reload itself, effectively breaking out of the sandbox altogether.

> The sandbox is still useful, however, as it disables plugins and popups, thus reducing the risk of the user being exposed to malware and other annoyances.

Since Fractal has full control over the content loaded within this iframe, I'm wondering what was the initial purpose of this attribute for the preview? Based on this, shall we remove it to keep the console clean?

**Comment by ahebrank** [comment]
Yeah, it seems like `sandbox` might have been there because of a misunderstanding of the standard.

Getting rid of it would mitigate the issue underlying #73
