### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Chapabu** [frctl/mandelbrot#77]
I cloned the repo to remove fractal as a dependency to fix the big new release blocker, and I couldn't successfully run `yarn` without the node-sass binaries failing compilation.

We should review the dependencies and see what we can get updated.

**Comment by sturobson** [comment]
running `npm audit` on a project where we're customising Mandelbrot I came across [this issue with the version of Lodash being used](https://www.npmjs.com/advisories/577). This is also a low level audit issue for @frctl/fractal too

**Comment by sturobson** [comment]
actually - to clarify the audit issues are for here in Mandelbrot:

@frctl/mandelbrot > @frctl/fractal > vorpal > inquirer > lodash

and here for fractal

@frctl/fractal > vorpal > inquirer > lodash

**Comment by Dan9boi** [comment]
when we've manually updated the dependencies, consider using [greenkeeper](https://greenkeeper.io/) for maintaining dependencies. It automatically makes a PR with the updated dependencies!

**Comment by Chapabu** [comment]
I thought we already had Greenkeeper enabled here. Perhaps it's only added on the main Fractal repo? Do you know @dkhuntrods?

**Comment by LeBenLeBen** [comment]
Fixed by #80, thanks @ahebrank !
