### ISSUE TITLE
Remove Nested Navigation State from LocalStorage

### ISSUE THREAD

**Issue by Maybach91** [frctl/mandelbrot#78]
Currently all the opened/closed nested Navigation states are save in LocalStorage. I think this behaviour is pretty uncommon and annoying. I can not imagine one single usecase, in which this would be helpful. 

The Quick'n'Dirty fix is currently to overwrite the [storage.js](https://github.com/frctl/mandelbrot/blob/3288912f32a8c0892303aa139c5e3198d61b442e/assets/js/storage.js) file within my own theme folder.

**Comment by LeBenLeBen** [comment]
I think it can be useful when you're refreshing a page, but for that specific purpose we could move to SessionStorage so it's not restored when you come back later.

Also the addition of a button that allows you to toggle all navigation items could help improve the experience.
