### ISSUE TITLE
Custom Favicon

### ISSUE THREAD

**Issue by julkue** [frctl/mandelbrot#99]
How to apply a custom favicon to mendelbrot? Unfortunately I didn't find something about this in the docs nor in the current issues.

**Comment by LeBenLeBen** [comment]
Mandelbrot config object has a `favicon` key you can set to point to your own favicon in your public directory. See https://github.com/frctl/mandelbrot/blob/develop/src/theme.js#L21

See https://fractal.build/guide/web/default-theme.html on how to configure Mandelbrot.

**Comment by julkue** [comment]
Great, works. Thanks for the hint. Maybe we can add this to the docs in v2.
